table Calendario
	lineageTag: c3d4e5f6-3344-5566-7788-99aabbcc0101

	column DateKey
		dataType: int64
		isKey
		formatString: 0
		lineageTag: d4e5f6a7-4455-6677-8899-aabbcc010101
		summarizeBy: none
		sourceColumn: DateKey

		annotation SummarizationSetBy = Automatic

	column Fecha
		dataType: dateTime
		formatString: yyyy-MM-dd
		lineageTag: e5f6a7b8-5566-7788-99aa-bbcc01010102
		summarizeBy: none
		sourceColumn: Fecha

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Anio
		dataType: int64
		formatString: 0
		lineageTag: f6a7b8c9-6677-8899-aabb-cc0101010301
		summarizeBy: none
		sourceColumn: Anio

		annotation SummarizationSetBy = Automatic

	column MesNumero
		dataType: int64
		formatString: 0
		lineageTag: a7b8c9d0-7788-99aa-bbcc-010101040101
		summarizeBy: none
		sourceColumn: MesNumero

		annotation SummarizationSetBy = Automatic

	column MesNombre
		dataType: string
		lineageTag: b8c9d0e1-8899-aabb-cc01-010105010101
		summarizeBy: none
		sourceColumn: MesNombre
		sortByColumn: MesNumero

		annotation SummarizationSetBy = Automatic

	column MesCorto
		dataType: string
		lineageTag: e8392110-3847-4958-8b9a-7c9b0e25184a
		summarizeBy: none
		sourceColumn: MesCorto
		sortByColumn: MesNumero

		annotation SummarizationSetBy = Automatic

	column Trimestre
		dataType: string
		lineageTag: c9d0e1f2-99aa-bbcc-0101-010601010101
		summarizeBy: none
		sourceColumn: Trimestre

		annotation SummarizationSetBy = Automatic

	column Semestre
		dataType: string
		lineageTag: d0e1f2a3-aabb-cc01-0101-010701010101
		summarizeBy: none
		sourceColumn: Semestre

		annotation SummarizationSetBy = Automatic

	column EsFinDeSemana
		dataType: int64
		formatString: 0
		lineageTag: e1f2a3b4-bbcc-0101-0101-010801010101
		summarizeBy: none
		sourceColumn: EsFinDeSemana

		annotation SummarizationSetBy = Automatic

	partition Calendario = m
		mode: import
		source =
				let
					Origen = Csv.Document(File.Contents(RutaDatos & "/Calendario.csv"), [Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
					Encabezados = Table.PromoteHeaders(Origen, [PromoteAllScalars = true]),
					Tipos = Table.TransformColumnTypes(Encabezados, {{"DateKey", Int64.Type}, {"Fecha", type date}, {"Anio", Int64.Type}, {"MesNumero", Int64.Type}, {"MesNombre", type text}, {"MesCorto", type text}, {"Trimestre", type text}, {"Semestre", type text}, {"EsFinDeSemana", Int64.Type}}, "en-US")
				in
					Tipos

