table PrecisionModelo
	lineageTag: 55cc74c4-b315-45cc-97f5-df9555ba5a96

	column OrdenModelo
		dataType: string
		lineageTag: 7cd947dd-5059-4d00-8e83-837039580264
		summarizeBy: none
		sourceColumn: OrdenModelo

		annotation SummarizationSetBy = Automatic

	column AIC
		dataType: double
		formatString: 0.00
		lineageTag: 6652d1e3-3777-4c07-baca-cd1d259bdfb8
		summarizeBy: none
		sourceColumn: AIC

		annotation SummarizationSetBy = Automatic

	column MAPE
		dataType: double
		formatString: 0.00"%"
		lineageTag: ef928a6a-5ecb-44e8-b502-a07132a4c6b3
		summarizeBy: none
		sourceColumn: MAPE

		annotation SummarizationSetBy = Automatic

	column RMSE
		dataType: double
		formatString: #,0.00
		lineageTag: aedd8d83-e802-4594-9ce8-9b7dbcf4b384
		summarizeBy: none
		sourceColumn: RMSE

		annotation SummarizationSetBy = Automatic

	column NTrain
		dataType: int64
		formatString: 0
		lineageTag: 340ac3f6-fda1-4c38-b0e6-6a55daaba834
		summarizeBy: none
		sourceColumn: NTrain

		annotation SummarizationSetBy = Automatic

	column NTest
		dataType: int64
		formatString: 0
		lineageTag: f7a85a28-960b-423e-b4f6-e6f2d6ba2f46
		summarizeBy: none
		sourceColumn: NTest

		annotation SummarizationSetBy = Automatic

	partition PrecisionModelo = m
		mode: import
		source =
				let
					Origen = Csv.Document(File.Contents(RutaDatos & "/PrecisionModelo.csv"), [Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
					Encabezados = Table.PromoteHeaders(Origen, [PromoteAllScalars = true]),
					Tipos = Table.TransformColumnTypes(Encabezados, {{"OrdenModelo", type text}, {"AIC", type number}, {"MAPE", type number}, {"RMSE", type number}, {"NTrain", Int64.Type}, {"NTest", Int64.Type}}, "en-US")
				in
					Tipos

	annotation PBI_ResultType = Table

