table GastosOperativos
	lineageTag: 3be66668-65d8-44f8-8331-b664f143e505

	column DateKey
		dataType: int64
		formatString: 0
		lineageTag: b596c925-95b5-486d-a6d8-189faa4a3c9e
		summarizeBy: none
		sourceColumn: DateKey

		annotation SummarizationSetBy = Automatic

	column AnioMes
		dataType: string
		lineageTag: f5940e2a-af26-4d6c-bbcb-fdb519468ded
		summarizeBy: none
		sourceColumn: AnioMes

		annotation SummarizationSetBy = Automatic

	column CentroCostoID
		dataType: string
		lineageTag: 175c38a6-8162-4202-9380-97e4c1d6b83f
		summarizeBy: none
		sourceColumn: CentroCostoID

		annotation SummarizationSetBy = Automatic

	column CuentaID
		dataType: string
		lineageTag: 735b297c-156e-4152-b0f4-d34b90dabf88
		summarizeBy: none
		sourceColumn: CuentaID

		annotation SummarizationSetBy = Automatic

	column OPEXPresupuestado
		dataType: double
		formatString: $#,##0.00;($#,##0.00);"-"
		lineageTag: edb8ba9f-8b70-4d49-9bdc-4087856406d9
		summarizeBy: sum
		sourceColumn: OPEXPresupuestado

		annotation SummarizationSetBy = Automatic

	column OPEXReal
		dataType: double
		formatString: $#,##0.00;($#,##0.00);"-"
		lineageTag: 00181f04-5e78-4d69-b228-26a09d68044e
		summarizeBy: sum
		sourceColumn: OPEXReal

		annotation SummarizationSetBy = Automatic

	column DesvioOPEX
		dataType: double
		formatString: $#,##0.00;($#,##0.00);"-"
		lineageTag: 13a17537-af5b-48ff-af9a-32829365f871
		summarizeBy: sum
		sourceColumn: DesvioOPEX

		annotation SummarizationSetBy = Automatic

	column DesvioPorcentual
		dataType: double
		formatString: +0.00%;-0.00%;0.00%
		lineageTag: bf38a6d8-0395-4679-bff9-55d164ccc501
		summarizeBy: average
		sourceColumn: DesvioPorcentual

		annotation SummarizationSetBy = Automatic

	partition GastosOperativos = m
		mode: import
		source =
				let
					Origen = Csv.Document(File.Contents(RutaDatos & "/GastosOperativos.csv"), [Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
					Encabezados = Table.PromoteHeaders(Origen, [PromoteAllScalars = true]),
					Tipos = Table.TransformColumnTypes(Encabezados, {{"DateKey", Int64.Type}, {"AnioMes", type text}, {"CentroCostoID", type text}, {"CuentaID", type text}, {"OPEXPresupuestado", type number}, {"OPEXReal", type number}, {"DesvioOPEX", type number}, {"DesvioPorcentual", type number}}, "en-US")
				in
					Tipos

