table fact_ventas_reales
	lineageTag: f4a5b6c7-0101-0101-0101-040101010101

	column TransaccionID
		dataType: string
		lineageTag: a5b6c7d8-0101-0101-0101-040201010101
		summarizeBy: none
		sourceColumn: TransaccionID

		annotation SummarizationSetBy = Automatic

	column DateKey
		dataType: int64
		formatString: 0
		lineageTag: b6c7d8e9-0101-0101-0101-040301010101
		summarizeBy: none
		sourceColumn: DateKey

		annotation SummarizationSetBy = Automatic

	column Fecha
		dataType: dateTime
		formatString: yyyy-MM-dd
		lineageTag: c7d8e9f0-0101-0101-0101-040401010101
		summarizeBy: none
		sourceColumn: Fecha

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column ProductoID
		dataType: string
		lineageTag: d8e9f0a1-0101-0101-0101-040501010101
		summarizeBy: none
		sourceColumn: ProductoID

		annotation SummarizationSetBy = Automatic

	column CentroCostoID
		dataType: string
		lineageTag: e9f0a1b2-0101-0101-0101-040601010101
		summarizeBy: none
		sourceColumn: CentroCostoID

		annotation SummarizationSetBy = Automatic

	column VolumenReal
		dataType: double
		formatString: #,##0.00
		lineageTag: f0a1b2c3-0101-0101-0101-040701010101
		summarizeBy: sum
		sourceColumn: VolumenReal

		annotation SummarizationSetBy = Automatic

	column PrecioRealUnit
		dataType: double
		formatString: $#,##0.00;($#,##0.00);"-"
		lineageTag: a1b2c3d4-0101-0101-0101-040801010101
		summarizeBy: average
		sourceColumn: PrecioRealUnit

		annotation SummarizationSetBy = Automatic

	column CostoRealUnit
		dataType: double
		formatString: $#,##0.00;($#,##0.00);"-"
		lineageTag: b2c3d4e5-0101-0101-0101-040901010101
		summarizeBy: average
		sourceColumn: CostoRealUnit

		annotation SummarizationSetBy = Automatic

	column IngresosReales
		dataType: double
		formatString: $#,##0.00;($#,##0.00);"-"
		lineageTag: c3d4e5f6-0101-0101-0101-041001010101
		summarizeBy: sum
		sourceColumn: IngresosReales

		annotation SummarizationSetBy = Automatic

	column CostoReal
		dataType: double
		formatString: $#,##0.00;($#,##0.00);"-"
		lineageTag: d4e5f6a7-0101-0101-0101-041101010101
		summarizeBy: sum
		sourceColumn: CostoReal

		annotation SummarizationSetBy = Automatic

	column MargenBrutoReal
		dataType: double
		formatString: $#,##0.00;($#,##0.00);"-"
		lineageTag: e5f6a7b8-0101-0101-0101-041201010101
		summarizeBy: sum
		sourceColumn: MargenBrutoReal

		annotation SummarizationSetBy = Automatic

	column CanalVenta
		dataType: string
		lineageTag: f6a7b8c9-0101-0101-0101-041301010101
		summarizeBy: none
		sourceColumn: CanalVenta

		annotation SummarizationSetBy = Automatic

	partition fact_ventas_reales = m
		mode: import
		source =
				let
					Origen = Csv.Document(File.Contents(RutaDatos & "/fact_ventas_reales.csv"), [Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
					Encabezados = Table.PromoteHeaders(Origen, [PromoteAllScalars = true]),
					Tipos = Table.TransformColumnTypes(Encabezados, {{"TransaccionID", type text}, {"DateKey", Int64.Type}, {"Fecha", type date}, {"ProductoID", type text}, {"CentroCostoID", type text}, {"VolumenReal", type number}, {"PrecioRealUnit", type number}, {"CostoRealUnit", type number}, {"IngresosReales", type number}, {"CostoReal", type number}, {"MargenBrutoReal", type number}, {"CanalVenta", type text}}, "en-US")
				in
					Tipos

