table fact_presupuesto_ventas
	lineageTag: 3f44eb99-8c48-4915-9f6a-a976aa239518

	column DateKey
		dataType: int64
		formatString: 0
		lineageTag: 6a09518d-57b5-473d-9e5f-8bb7a7d92bd8
		summarizeBy: none
		sourceColumn: DateKey

		annotation SummarizationSetBy = Automatic

	column AnioMes
		dataType: string
		lineageTag: b942e7cc-a465-42cb-8729-4f23688688e7
		summarizeBy: none
		sourceColumn: AnioMes

		annotation SummarizationSetBy = Automatic

	column ProductoID
		dataType: string
		lineageTag: 3fef048a-81ce-42d5-913f-3f8647784145
		summarizeBy: none
		sourceColumn: ProductoID

		annotation SummarizationSetBy = Automatic

	column CentroCostoID
		dataType: string
		lineageTag: 1460c0d5-0bdc-4cd1-b0cf-8d230fb12e77
		summarizeBy: none
		sourceColumn: CentroCostoID

		annotation SummarizationSetBy = Automatic

	column VolumenPresupuestado
		dataType: int64
		formatString: #,##0
		lineageTag: e1349a86-30a9-4bdf-82b6-6f0d166e6640
		summarizeBy: sum
		sourceColumn: VolumenPresupuestado

		annotation SummarizationSetBy = Automatic

	column PrecioPresupuestadoUnit
		dataType: double
		formatString: $#,##0.00;($#,##0.00);"-"
		lineageTag: 85a8acc7-a74c-4f9a-a74b-085b84e5f3ab
		summarizeBy: average
		sourceColumn: PrecioPresupuestadoUnit

		annotation SummarizationSetBy = Automatic

	column CostoEstandarUnit
		dataType: double
		formatString: $#,##0.00;($#,##0.00);"-"
		lineageTag: c29a6c09-7c98-4525-aac2-f6cbe7ea4582
		summarizeBy: average
		sourceColumn: CostoEstandarUnit

		annotation SummarizationSetBy = Automatic

	column IngresosPresupuestados
		dataType: double
		formatString: $#,##0.00;($#,##0.00);"-"
		lineageTag: 078d9389-6fc4-4727-bea2-5e654244be8e
		summarizeBy: sum
		sourceColumn: IngresosPresupuestados

		annotation SummarizationSetBy = Automatic

	column CostoPresupuestado
		dataType: double
		formatString: $#,##0.00;($#,##0.00);"-"
		lineageTag: 11ae4547-407b-4916-b614-b240d788f7d4
		summarizeBy: sum
		sourceColumn: CostoPresupuestado

		annotation SummarizationSetBy = Automatic

	column MargenBrutoPresupuestado
		dataType: double
		formatString: $#,##0.00;($#,##0.00);"-"
		lineageTag: bd638ede-9e49-4f8e-9d75-8601e6de15c9
		summarizeBy: sum
		sourceColumn: MargenBrutoPresupuestado

		annotation SummarizationSetBy = Automatic

	partition fact_presupuesto_ventas = m
		mode: import
		source =
				let
					Origen = Csv.Document(File.Contents(RutaDatos & "/fact_presupuesto_ventas.csv"), [Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
					Encabezados = Table.PromoteHeaders(Origen, [PromoteAllScalars = true]),
					Tipos = Table.TransformColumnTypes(Encabezados, {{"DateKey", Int64.Type}, {"AnioMes", type text}, {"ProductoID", type text}, {"CentroCostoID", type text}, {"VolumenPresupuestado", Int64.Type}, {"PrecioPresupuestadoUnit", type number}, {"CostoEstandarUnit", type number}, {"IngresosPresupuestados", type number}, {"CostoPresupuestado", type number}, {"MargenBrutoPresupuestado", type number}}, "en-US")
				in
					Tipos

