table PronosticoDemanda
	lineageTag: b1d3e252-b3d7-4ab0-bbc9-059c5d58d98e

	column Fecha
		dataType: dateTime
		formatString: yyyy-MM-dd
		lineageTag: 5b31c6c4-5c5b-48eb-8803-192603c10b41
		summarizeBy: none
		sourceColumn: Fecha

		annotation SummarizationSetBy = Automatic

	column DateKey
		dataType: int64
		formatString: 0
		lineageTag: 4db9ef5a-cb26-45b8-90fc-a9c2fcd2aec6
		summarizeBy: none
		sourceColumn: DateKey

		annotation SummarizationSetBy = Automatic

	column VolumenReal
		dataType: double
		formatString: #,0
		lineageTag: 618b769c-596a-4716-99d3-3f1fc84dc724
		summarizeBy: sum
		sourceColumn: VolumenReal

		annotation SummarizationSetBy = Automatic

	column VolumenForecast
		dataType: double
		formatString: #,0
		lineageTag: 98949438-391d-4752-9069-931a0cae2ede
		summarizeBy: sum
		sourceColumn: VolumenForecast

		annotation SummarizationSetBy = Automatic

	column IC95_Inferior
		dataType: double
		formatString: #,0
		lineageTag: fe1fe0a1-242c-423e-8ff0-8994ea8934c0
		summarizeBy: sum
		sourceColumn: IC95_Inferior

		annotation SummarizationSetBy = Automatic

	column IC95_Superior
		dataType: double
		formatString: #,0
		lineageTag: 7d412534-775c-4f4c-ac37-5c472ceb3a23
		summarizeBy: sum
		sourceColumn: IC95_Superior

		annotation SummarizationSetBy = Automatic

	partition PronosticoDemanda = m
		mode: import
		source =
				let
					Origen = Csv.Document(File.Contents(RutaDatos & "/PronosticoDemanda.csv"), [Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
					Encabezados = Table.PromoteHeaders(Origen, [PromoteAllScalars = true]),
					Tipos = Table.TransformColumnTypes(Encabezados, {{"Fecha", type date}, {"DateKey", Int64.Type}, {"VolumenReal", type number}, {"VolumenForecast", type number}, {"IC95_Inferior", type number}, {"IC95_Superior", type number}}, "en-US")
				in
					Tipos

	annotation PBI_ResultType = Table
