table fact_presupuesto_ventas
	lineageTag: a7b8c9d0-0101-0101-0101-050101010101

	column DateKey
		dataType: int64
		formatString: 0
		lineageTag: b8c9d0e1-0101-0101-0101-050201010101
		summarizeBy: none
		sourceColumn: DateKey

		annotation SummarizationSetBy = Automatic

	column AnioMes
		dataType: string
		lineageTag: c9d0e1f2-0101-0101-0101-050301010101
		summarizeBy: none
		sourceColumn: AnioMes

		annotation SummarizationSetBy = Automatic

	column ProductoID
		dataType: string
		lineageTag: d0e1f2a3-0101-0101-0101-050401010101
		summarizeBy: none
		sourceColumn: ProductoID

		annotation SummarizationSetBy = Automatic

	column CentroCostoID
		dataType: string
		lineageTag: e1f2a3b4-0101-0101-0101-050501010101
		summarizeBy: none
		sourceColumn: CentroCostoID

		annotation SummarizationSetBy = Automatic

	column VolumenPresupuestado
		dataType: int64
		formatString: #,##0
		lineageTag: f2a3b4c5-0101-0101-0101-050601010101
		summarizeBy: sum
		sourceColumn: VolumenPresupuestado

		annotation SummarizationSetBy = Automatic

	column PrecioPresupuestadoUnit
		dataType: double
		formatString: $#,##0.00;($#,##0.00);"-"
		lineageTag: a3b4c5d6-0101-0101-0101-050701010101
		summarizeBy: average
		sourceColumn: PrecioPresupuestadoUnit

		annotation SummarizationSetBy = Automatic

	column CostoEstandarUnit
		dataType: double
		formatString: $#,##0.00;($#,##0.00);"-"
		lineageTag: b4c5d6e7-0101-0101-0101-050801010101
		summarizeBy: average
		sourceColumn: CostoEstandarUnit

		annotation SummarizationSetBy = Automatic

	column IngresosPresupuestados
		dataType: double
		formatString: $#,##0.00;($#,##0.00);"-"
		lineageTag: c5d6e7f8-0101-0101-0101-050901010101
		summarizeBy: sum
		sourceColumn: IngresosPresupuestados

		annotation SummarizationSetBy = Automatic

	column CostoPresupuestado
		dataType: double
		formatString: $#,##0.00;($#,##0.00);"-"
		lineageTag: d6e7f8a9-0101-0101-0101-051001010101
		summarizeBy: sum
		sourceColumn: CostoPresupuestado

		annotation SummarizationSetBy = Automatic

	column MargenBrutoPresupuestado
		dataType: double
		formatString: $#,##0.00;($#,##0.00);"-"
		lineageTag: e7f8a9b0-0101-0101-0101-051101010101
		summarizeBy: sum
		sourceColumn: MargenBrutoPresupuestado

		annotation SummarizationSetBy = Automatic

	partition fact_presupuesto_ventas = m
		mode: import
		source =
				let
					Origen = Csv.Document(File.Contents(RutaDatos & "/fact_presupuesto_ventas.csv"), [Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
					Encabezados = Table.PromoteHeaders(Origen, [PromoteAllScalars = true]),
					Tipos = Table.TransformColumnTypes(Encabezados, {{"DateKey", Int64.Type}, {"AnioMes", type text}, {"ProductoID", type text}, {"CentroCostoID", type text}, {"VolumenPresupuestado", Int64.Type}, {"PrecioPresupuestadoUnit", type number}, {"CostoEstandarUnit", type number}, {"IngresosPresupuestados", type number}, {"CostoPresupuestado", type number}, {"MargenBrutoPresupuestado", type number}}, "en-US")
				in
					Tipos

