table dim_centros_costo
	lineageTag: 6716561a-d8fa-4ebd-9734-7e77cad06f55

	column CentroCostoID
		dataType: string
		isKey
		lineageTag: 4eb0b854-2ed6-4bb3-849c-3b0affd8c846
		summarizeBy: none
		sourceColumn: CentroCostoID

		annotation SummarizationSetBy = Automatic

	column NombreCentroCosto
		dataType: string
		lineageTag: fcada9e7-f8ff-4157-97b0-6e4d3d4e9aa6
		summarizeBy: none
		sourceColumn: NombreCentroCosto

		annotation SummarizationSetBy = Automatic

	column Area
		dataType: string
		lineageTag: 6cec07f6-9815-4edc-9e4e-7de288f26c56
		summarizeBy: none
		sourceColumn: Area

		annotation SummarizationSetBy = Automatic

	column Responsable
		dataType: string
		lineageTag: 06980ed1-884f-42c5-9fd8-ce9ace6cb8f4
		summarizeBy: none
		sourceColumn: Responsable

		annotation SummarizationSetBy = Automatic

	partition dim_centros_costo = m
		mode: import
		source =
				let
					Origen = Csv.Document(File.Contents(RutaDatos & "/dim_centros_costo.csv"), [Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
					Encabezados = Table.PromoteHeaders(Origen, [PromoteAllScalars = true]),
					Tipos = Table.TransformColumnTypes(Encabezados, {{"CentroCostoID", type text}, {"NombreCentroCosto", type text}, {"Area", type text}, {"Responsable", type text}}, "en-US")
				in
					Tipos
