table fact_capital_trabajo
	lineageTag: dc27372a-a413-4009-a403-df8e0689eb54

	column DateKey
		dataType: int64
		formatString: 0
		lineageTag: cb46f1c0-d099-4d91-8308-d3afe0b35260
		summarizeBy: none
		sourceColumn: DateKey

		annotation SummarizationSetBy = Automatic

	column AnioMes
		dataType: string
		lineageTag: ea5cd631-c54c-4f70-bb42-fd4c5388a83d
		summarizeBy: none
		sourceColumn: AnioMes

		annotation SummarizationSetBy = Automatic

	column CuentasPorCobrar
		dataType: double
		formatString: $#,##0.00;($#,##0.00);"-"
		lineageTag: 20ae65a4-3681-4fad-b0df-8736fcc1f33a
		summarizeBy: average
		sourceColumn: CuentasPorCobrar

		annotation SummarizationSetBy = Automatic

	column CuentasPorPagar
		dataType: double
		formatString: $#,##0.00;($#,##0.00);"-"
		lineageTag: 1591ee58-497c-489c-ab85-4ee23dd40e94
		summarizeBy: average
		sourceColumn: CuentasPorPagar

		annotation SummarizationSetBy = Automatic

	column Inventario
		dataType: double
		formatString: $#,##0.00;($#,##0.00);"-"
		lineageTag: d7e6ee47-f025-466a-b69c-fdb1ad092b92
		summarizeBy: average
		sourceColumn: Inventario

		annotation SummarizationSetBy = Automatic

	column DSO_DiasCobro
		dataType: double
		formatString: 0.0 "días"
		lineageTag: f9a7c1b1-7250-4d47-9e6a-19171785a55f
		summarizeBy: average
		sourceColumn: DSO_DiasCobro

		annotation SummarizationSetBy = Automatic

	column DIO_DiasInventario
		dataType: double
		formatString: 0.0 "días"
		lineageTag: 1330d7d7-53a1-423d-9358-4b2f9bcddd0e
		summarizeBy: average
		sourceColumn: DIO_DiasInventario

		annotation SummarizationSetBy = Automatic

	column DPO_DiasPago
		dataType: double
		formatString: 0.0 "días"
		lineageTag: 287dcf7c-4601-468f-9b2a-634ff5910225
		summarizeBy: average
		sourceColumn: DPO_DiasPago

		annotation SummarizationSetBy = Automatic

	column CicloConversionEfectivo_CCC
		dataType: double
		formatString: 0.0 "días"
		lineageTag: da5e494e-da6a-481f-a3a7-39dff87de482
		summarizeBy: average
		sourceColumn: CicloConversionEfectivo_CCC

		annotation SummarizationSetBy = Automatic

	column NecesidadOperativaFondos_NOF
		dataType: double
		formatString: $#,##0.00;($#,##0.00);"-"
		lineageTag: 1859e23c-5166-4ad7-989b-8220d78525c2
		summarizeBy: average
		sourceColumn: NecesidadOperativaFondos_NOF

		annotation SummarizationSetBy = Automatic

	partition fact_capital_trabajo = m
		mode: import
		source =
				let
					Origen = Csv.Document(File.Contents(RutaDatos & "/fact_capital_trabajo.csv"), [Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
					Encabezados = Table.PromoteHeaders(Origen, [PromoteAllScalars = true]),
					Tipos = Table.TransformColumnTypes(Encabezados, {{"DateKey", Int64.Type}, {"AnioMes", type text}, {"CuentasPorCobrar", type number}, {"CuentasPorPagar", type number}, {"Inventario", type number}, {"DSO_DiasCobro", type number}, {"DIO_DiasInventario", type number}, {"DPO_DiasPago", type number}, {"CicloConversionEfectivo_CCC", type number}, {"NecesidadOperativaFondos_NOF", type number}}, "en-US")
				in
					Tipos

