table fact_opex_mensual
	lineageTag: 14bd16c2-0dcd-4b19-be6b-2db9c6af7006

	column DateKey
		dataType: int64
		formatString: 0
		lineageTag: cf76e3dd-e10b-43d9-8f02-3eae85ff9625
		summarizeBy: none
		sourceColumn: DateKey

		annotation SummarizationSetBy = Automatic

	column AnioMes
		dataType: string
		lineageTag: ca4ce512-ee4c-4109-972e-027d1be7eaea
		summarizeBy: none
		sourceColumn: AnioMes

		annotation SummarizationSetBy = Automatic

	column CentroCostoID
		dataType: string
		lineageTag: b008929d-373a-4713-9380-59c8ae8f4aa4
		summarizeBy: none
		sourceColumn: CentroCostoID

		annotation SummarizationSetBy = Automatic

	column CuentaID
		dataType: string
		lineageTag: 46b08e56-ced7-48ee-ac8f-903cedc7439e
		summarizeBy: none
		sourceColumn: CuentaID

		annotation SummarizationSetBy = Automatic

	column OPEXPresupuestado
		dataType: double
		formatString: $#,##0.00;($#,##0.00);"-"
		lineageTag: ee1f0aa1-2f59-4878-8321-70cb95d48cc9
		summarizeBy: sum
		sourceColumn: OPEXPresupuestado

		annotation SummarizationSetBy = Automatic

	column OPEXReal
		dataType: double
		formatString: $#,##0.00;($#,##0.00);"-"
		lineageTag: 82363219-37de-4738-bfc4-4813b016ecde
		summarizeBy: sum
		sourceColumn: OPEXReal

		annotation SummarizationSetBy = Automatic

	column DesvioOPEX
		dataType: double
		formatString: +$#,##0.00;-$#,##0.00;"-"
		lineageTag: ea978d3f-9850-4dde-b185-dba7866b0638
		summarizeBy: sum
		sourceColumn: DesvioOPEX

		annotation SummarizationSetBy = Automatic

	column DesvioPorcentual
		dataType: double
		formatString: +0.00%;-0.00%;0.00%
		lineageTag: c4611e91-ea42-4e06-bd90-dc89809c0fcc
		summarizeBy: average
		sourceColumn: DesvioPorcentual

		annotation SummarizationSetBy = Automatic

	partition fact_opex_mensual = m
		mode: import
		source =
				let
					Origen = Csv.Document(File.Contents(RutaDatos & "/fact_opex_mensual.csv"), [Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
					Encabezados = Table.PromoteHeaders(Origen, [PromoteAllScalars = true]),
					Tipos = Table.TransformColumnTypes(Encabezados, {{"DateKey", Int64.Type}, {"AnioMes", type text}, {"CentroCostoID", type text}, {"CuentaID", type text}, {"OPEXPresupuestado", type number}, {"OPEXReal", type number}, {"DesvioOPEX", type number}, {"DesvioPorcentual", type number}}, "en-US")
				in
					Tipos

