table InventarioGuarda
	lineageTag: e48b1a32-9c12-4e58-97ef-4179d854a201

	column DateKey
		dataType: int64
		formatString: 0
		lineageTag: a72b94f1-6102-4d51-b844-3259e812b101
		summarizeBy: none
		sourceColumn: DateKey

		annotation SummarizationSetBy = Automatic

	column AnioMes
		dataType: string
		lineageTag: b83c05e2-7213-4e62-c955-4360f923c202
		summarizeBy: none
		sourceColumn: AnioMes

		annotation SummarizationSetBy = Automatic

	column ProductoID
		dataType: string
		lineageTag: c94d16f3-8324-4f73-da66-5471a034d303
		summarizeBy: none
		sourceColumn: ProductoID

		annotation SummarizationSetBy = Automatic

	column TipoVasija
		dataType: string
		lineageTag: da5e27a4-9435-4084-eb77-6582b145e404
		summarizeBy: none
		sourceColumn: TipoVasija

		annotation SummarizationSetBy = Automatic

	column Litros
		dataType: double
		formatString: #,##0.0 "L"
		lineageTag: eb6f38b5-a546-4195-fc88-7693c256f505
		summarizeBy: sum
		sourceColumn: Litros

		annotation SummarizationSetBy = Automatic

	column ValorInventario
		dataType: double
		formatString: $#,##0;($#,##0);"-"
		lineageTag: fc7049c6-b657-42a6-0d99-8704d367a606
		summarizeBy: sum
		sourceColumn: ValorInventario

		annotation SummarizationSetBy = Automatic

	column MermaPct
		dataType: double
		formatString: 0.00%
		lineageTag: 0d815ad7-c768-43b7-1e0a-9815e478b707
		summarizeBy: average
		sourceColumn: MermaPct

		annotation SummarizationSetBy = Automatic

	column DIODias
		dataType: double
		formatString: 0.0 "días"
		lineageTag: 1e926be8-d879-44c8-2f1b-0926f589c808
		summarizeBy: average
		sourceColumn: DIODias

		annotation SummarizationSetBy = Automatic

	column EstadoCalidad
		dataType: string
		lineageTag: 2fa37cf9-e98a-45d9-302c-1a37a69ad909
		summarizeBy: none
		sourceColumn: EstadoCalidad

		annotation SummarizationSetBy = Automatic

	partition InventarioGuarda = m
		mode: import
		source =
				let
					Origen = Csv.Document(File.Contents(RutaDatos & "/InventarioGuarda.csv"), [Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
					Encabezados = Table.PromoteHeaders(Origen, [PromoteAllScalars = true]),
					Tipos = Table.TransformColumnTypes(Encabezados, {{"DateKey", Int64.Type}, {"AnioMes", type text}, {"ProductoID", type text}, {"TipoVasija", type text}, {"Litros", type number}, {"ValorInventario", type number}, {"MermaPct", type number}, {"DIODias", type number}, {"EstadoCalidad", type text}}, "en-US")
				in
					Tipos

