table ProduccionPlanta
	lineageTag: 7052a44d-02f5-40e9-9ef1-2fdb9e9d165a

	column RemitoID
		dataType: string
		isKey
		lineageTag: 548a2112-8f59-4305-a585-341f1478294f
		summarizeBy: none
		sourceColumn: RemitoID

		annotation SummarizationSetBy = Automatic

	column DateKey
		dataType: int64
		formatString: 0
		lineageTag: 4b036bcf-ba7d-4125-8b93-4f13046af8c7
		summarizeBy: none
		sourceColumn: DateKey

		annotation SummarizationSetBy = Automatic

	column Fecha
		dataType: dateTime
		formatString: yyyy-mm-dd
		lineageTag: 9c5d9d88-1579-485f-8fc4-eb56a3a5b389
		summarizeBy: none
		sourceColumn: Fecha

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column CentroCostoID
		dataType: string
		lineageTag: 8103d4e2-7ea7-4ed9-91f8-53e70a77dddf
		summarizeBy: none
		sourceColumn: CentroCostoID

		annotation SummarizationSetBy = Automatic

	column VariedadUva
		dataType: string
		lineageTag: 1d1111b4-e029-4a68-b557-7901531987e0
		summarizeBy: none
		sourceColumn: VariedadUva

		annotation SummarizationSetBy = Automatic

	column FincaOrigen
		dataType: string
		lineageTag: 198bdb92-6645-44ba-987d-043f87373696
		summarizeBy: none
		sourceColumn: FincaOrigen

		annotation SummarizationSetBy = Automatic

	column KilosEntrada
		dataType: double
		formatString: #,##0.0 "kg"
		lineageTag: f80cca7b-b9cb-48fc-85ce-345cf1d85d70
		summarizeBy: sum
		sourceColumn: KilosEntrada

		annotation SummarizationSetBy = Automatic

	column GradosBrix
		dataType: double
		formatString: 0.0 "°Bx"
		lineageTag: a7f41755-d700-4ad1-8fa4-3ef441bf34ae
		summarizeBy: average
		sourceColumn: GradosBrix

		annotation SummarizationSetBy = Automatic

	column LitrosMostoObtenido
		dataType: double
		formatString: #,##0.0 "L"
		lineageTag: 84aff5e3-1d4e-4f18-9e59-af734d8cd3a0
		summarizeBy: sum
		sourceColumn: LitrosMostoObtenido

		annotation SummarizationSetBy = Automatic

	column RendimientoExtraccionPct
		dataType: double
		formatString: 0.00%
		lineageTag: f3904883-7ba4-498d-94a3-a376196ca864
		summarizeBy: average
		sourceColumn: RendimientoExtraccionPct

		annotation SummarizationSetBy = Automatic

	column CalificacionSanitaria
		dataType: string
		lineageTag: 0985c167-fbd0-4723-a24f-d6ab4d9e3c7b
		summarizeBy: none
		sourceColumn: CalificacionSanitaria

		annotation SummarizationSetBy = Automatic

	column UbicacionGeografica
		dataType: string
		lineageTag: c87b411d-3b89-4f21-825e-3847291a9988
		dataCategory: Place
		summarizeBy: none
		sourceColumn: UbicacionGeografica

		annotation SummarizationSetBy = Automatic

	column Latitud
		dataType: double
		formatString: 0.0000
		lineageTag: 71092e01-3b89-4f21-825e-3847291a0001
		dataCategory: Latitude
		summarizeBy: average
		sourceColumn: Latitud

		annotation SummarizationSetBy = Automatic

	column Longitud
		dataType: double
		formatString: 0.0000
		lineageTag: 71092e02-3b89-4f21-825e-3847291a0002
		dataCategory: Longitude
		summarizeBy: average
		sourceColumn: Longitud

		annotation SummarizationSetBy = Automatic

	partition ProduccionPlanta = m
		mode: import
		source =
				let
					Origen = Csv.Document(File.Contents(RutaDatos & "/ProduccionPlanta.csv"), [Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
					Encabezados = Table.PromoteHeaders(Origen, [PromoteAllScalars = true]),
					Tipos = Table.TransformColumnTypes(Encabezados, {{"RemitoID", type text}, {"DateKey", Int64.Type}, {"Fecha", type date}, {"CentroCostoID", type text}, {"VariedadUva", type text}, {"FincaOrigen", type text}, {"KilosEntrada", type number}, {"GradosBrix", type number}, {"LitrosMostoObtenido", type number}, {"RendimientoExtraccionPct", type number}, {"CalificacionSanitaria", type text}, {"UbicacionGeografica", type text}, {"Latitud", type number}, {"Longitud", type number}}, "en-US")
				in
					Tipos

